### ISSUE TITLE
terser is undefined?

### ISSUE THREAD

**Issue by devanshbatra04** [webpack-contrib/terser-webpack-plugin#68] opened 2019-02-02 20:37 UTC
* Operating System: Ubuntu 16.04 
* Node Version: v9.10.0 
* NPM Version: v5.6.0
* webpack Version: v4
* terser-webpack-plugin Version: v1.1.0

### Expected Behavior

This should not happen, the build should work as expected.

### Actual Behavior
I try to run the angular build, this set of errors props up, pretty sure it's related to terser. I looked up the ```dist/minify.js``` apparantly ```_terser2``` is undefined

![screenshot from 2019-02-03 01-51-53](https://user-images.githubusercontent.com/33961252/52169034-079f5a80-2758-11e9-8549-ba1cf3aa6ee7.png)

**Comment by kasparsd** [comment] 2019-02-02 20:49
I'm getting the same issue. Here is a sample [Travis CI run](https://travis-ci.com/kasparsd/burti/jobs/174893751).

```
js/app.1b05abb2.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/home/travis/build/kasparsd/burti/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at TaskRunner.boundWorkers (/home/travis/build/kasparsd/burti/node_modules/terser-webpack-plugin/dist/TaskRunner.js:68:40)
    at enqueue (/home/travis/build/kasparsd/burti/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:14)
    at tryCatcher (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/kasparsd/burti/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
```

**Comment by kasparsd** [comment] 2019-02-02 20:53
Appears to be a duplicate of #67.

**Comment by pitops** [comment] 2019-02-02 20:54
See #66 for a workaround

**Closed** 2019-02-02 20:59 UTC
