### ISSUE TITLE
 "92% chunk asset optimization TerserPlugin" reactjs

### ISSUE THREAD

**Issue by theshashiverma** [webpack-contrib/terser-webpack-plugin#217] opened 2020-02-07 08:38 UTC
- Operating System: ubuntu 18.04
- Node Version:12.13.1
- NPM Version:6.12.1
- webpack Version: 4
- terser-webpack-plugin Version: 2.3.2

### Expected Behavior

When I am running npm start, compilation takes a little pause at 92%, basically, the full message is "92% chunk asset optimization TerserPlugin" and after 8-10 seconds it shows the final result

### Code
module.exports = {

	optimization: {
		minimize: true,
		minimizer: [
			new TerserPlugin({
				cache: true,
				parallel: true,
				sourceMap: true,
				terserOptions: {
					compress: false,
					ecma: 8,
					mangle: true
				}
			})
		],
	},	
	
};

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment] 2020-02-07 10:18
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please fill 

> How Do We Reproduce?

You can create reproducible test repo, without additional information we can't help, sorry

**Closed by evilebottnawi** 2020-02-07 10:18 UTC

**Comment by evilebottnawi** [comment] 2020-02-07 10:19
> When I am running npm start, compilation takes a little pause at 92%, basically, the full message is "92% chunk asset optimization TerserPlugin" and after 8-10 seconds it shows the final result

Because uglification require time, it is not the fast action.
